### Get Reset Password Token
# @name token
POST http://localhost:3000/api/v1/auth/emailpass/reset-password/token
Content-Type: application/json
Authorization: Bearer {{$dotenv TESTING_API_KEY}}

{
  "email": "test@example.com"
}

### Reset password
POST http://localhost:3000/api/v1/auth/emailpass/reset-password
Content-Type: application/json
Authorization: Bearer {{$dotenv TESTING_API_KEY}}

{
  "email": "test@example.com",
  "token": "{{token.response.body.data.token}}",
  "password": "newpassword"
}