apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mswa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git"
    targetRevision: bryan/web-file-encryption
    path: .kube
    directory:
      - path: apps.yaml
        exclude: true
  destination:
    name: "http://kubernetes.default.svc"
    namespace: mswa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true