apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mswa-prod
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
      revision: bryan/web-file-encryption
      directories:
      - path: .kube/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
        targetRevision: bryan/web-file-encryption
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
