@baseUrl = {{$dotenv baseUrl}}
@tenantId = {{$dotenv tenantId}}
@unitId = {{$dotenv unitId}}
@userId = {{$dotenv userId}}

### Create a new unit
POST {{baseUrl}}/tenant/{{tenantId}}/units
Content-Type: application/json

{
  "adminUserId": "{{userId}}"
}

### Update a unit
PUT {{baseUrl}}/tenant/{{tenantId}}/unit/{{unitId}}
Content-Type: application/json

{
  "adminUserId": "{{userId}}"
}

### Create an invite token
POST {{baseUrl}}/tenant/{{tenantId}}/unit/{{unitId}}/invite
Content-Type: application/json

{}