@baseUrl = {{$dotenv baseUrl}}
@tenantId = {{$dotenv tenantId}}
@unitId = {{$dotenv unitId}}
@userId = {{$dotenv userId}}
@token = {{$dotenv token}}

### Accept an invite
POST {{baseUrl}}/unit/invite/accept?token={{token}}
Content-Type: application/json

{
  "userId": "{{userId}}"
}

### List users in a unit
GET {{baseUrl}}/tenant/{{tenantId}}/unit/{{unitId}}/users?fields=id,email&limit=10&offset=0
Content-Type: application/json

### Remove a user from a unit
DELETE {{baseUrl}}/tenant/{{tenantId}}/unit/{{unitId}}/users/{{userId}}
Content-Type: application/json