apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mobiliy-scooter-web-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
      revision: bryan/cooldown-2
      directories:
      - path: apps/*
        recurse: true
  template:
    metadata:
      name: 'mswa-{{.path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
        targetRevision: bryan/cooldown-2
        path: '{{.path.path}}/.kube'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        automated:
          prune: true
          selfHeal: true
