version: '3.7'

services:
  db:
    image: "supabase/postgres:15.6.1.113"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      
volumes:
 db: