services:
  db:
    build: ./docker/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  kv:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - kv:/data
    restart: always
  queue:
    image: "rabbitmq:3"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue:/var/lib/rabbitmq
  vault:
    image: hashicorp/vault:latest
    network_mode: "host"
    volumes:
      - vault:/vault/file
      - ./docker/vault/init.sh:/init.sh
    command: sh /init.sh
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
  smtp:
    image: boky/postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=example.com
    ports:
      - "25:25"
      - "1587:587"
  storage:
    image: "minio/minio"
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    depends_on:
      - queue
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_NOTIFY_AMQP_ENABLE_put_video: "on"
      MINIO_NOTIFY_AMQP_URL_put_video: "amqp://guest:guest@localhost:5672/"
      MINIO_NOTIFY_AMQP_EXCHANGE_put_video: "storage"
      MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_put_video: "direct"
      MINIO_NOTIFY_AMQP_ROUTING_KEY_put_video: "videos.put"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - storage:/data
volumes:
 db:
 kv:
 queue:
 storage:
 vault:
