services:
  cert-generator:
    image: alpine/curl
    volumes:
      - certs:/certs
    command: >
      sh -c '
        curl https://github.com/minio/certgen/releases/latest/download/certgen-linux-amd64 -o /usr/local/bin/certgen &&
        chmod +x /usr/local/bin/certgen &&
        certgen --host localhost &&
        chown -R 1001:0 /certs
      '
  db:
    build: ./packages/docker/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  kv:
    image: bitnami/valkey:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_LISTENERS_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

  vault:
    image: bitnami/vault:latest
    user: root
    volumes:
      - vault:/vault/file
      - ./packages/docker/vault/init.sh:/init.sh
    entrypoint: sh /init.sh
    ports:
      - 8200:8200
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK # Needed for vault
  storage:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      cert-generator:
        condition: service_completed_successfully # Ensure certs are generated
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_SCHEME: "https"
    entrypoint: |
      sh -c '
        chown -R 1001:0 /certs &&
        exec /opt/bitnami/scripts/minio/run.sh
      '
    volumes:
      - storage:/bitnami/data
      - certs:/certs # Mount the shared certificate volume

volumes:
  db:
  storage:
  kafka:
  vault:
  certs: # Define the shared volume for certificates
