services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
  
  kv:
    image: valkey/valkey:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  queue:
    image: redpandadata/redpanda
    volumes:
      - queue:/var/lib/redpanda/data
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS_ENABLE=true
      - REDPANDA_ADVERTISED_LISTENERS=PLAINTEXT://queue:9092

  api:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/api:develop
    env_file:
      - .env.api
    depends_on:
      - db
      - kv

  worker:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/worker:develop
    env_file:
      - .env.worker
    depends_on:
      - db
      - queue

  web:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/web:develop
    env_file:
      - .env.web
    depends_on:
      - api

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - api

volumes:
  db:
  queue:
  caddy_data:
  caddy_config: