services:
  db:
    build: ./docker/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  kv:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  queue:
    image: redpandadata/redpanda
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - queue:/var/lib/redpanda/data
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS_ENABLE=true
      - REDPANDA_ADVERTISED_LISTENERS=PLAINTEXT://

volumes:
  db:
  queue: