services:
  db:
    build: ./docker/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_EXTENSIONS: "pg_cron"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
 db: