services:
  db:
    build: ./docker/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  kv:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - kv:/data
    restart: always
  queue:
    image: "rabbitmq:3"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue:/var/lib/rabbitmq
  storage:
    image: "minio/minio"
    command: server --console-address ":9001" /data
    network_mode: "host"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_NOTIFY_WEBHOOK_ENABLE_put_videos: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_put_videos: http://localhost:3000/v1/api/webhooks/storage/videos
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - storage:/data
volumes:
 db:
 kv:
 queue:
 storage: