services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
  
  kv:
    image: valkey/valkey:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  
  queue:
    image: redpandadata/redpanda
    volumes:
      - queue:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --check=false
      - --node-id
      - "0"
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://queue:9092

  api:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/api:develop
    env_file:
      - .env.api
    depends_on:
      - db
      - kv
      - queue

  worker:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/worker:develop
    env_file:
      - .env.worker
    depends_on:
      - db
      - queue
    gpus: all
    shm_size: "8gb"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

  web:
    image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/web:develop
    env_file:
      - .env.web
    depends_on:
      - api

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - api

volumes:
  db:
  queue:
  caddy_data:
  caddy_config: