apiVersion: apps/v1
kind: Deployment
metadata:
  name: mswa-timescaledb
  namespace: mswa-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mswa-timescaledb
  template:
    metadata:
      labels:
        app: mswa-timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg17
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password" # TODO: Change this to a real secret
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 10
