apiVersion: v1
kind: PersistentVolume
metadata:
  name: mswa-timescaledb-pv
  namespace: mswa-api
spec:
  storageClassName: csi-cinder-sc-retain
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce