apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-{{ .Values.app.name }}-config
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
data:
    API_BASE_URL: {{ .Values.configmap.data.API_BASE_URL }}
    API_KEY: {{ .Values.configmap.data.API_KEY }}