apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-{{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
spec:
    replicas: {{ .Values.app.replicas }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-{{ .Values.app.name }}
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-{{ .Values.app.name }}
        spec:
            containers:
                - name: {{ .Release.Name }}-{{ .Values.app.name }}
                  image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
                  ports:
                      - containerPort: {{ .Values.app.port }}
                  env:
                    configMapRef:
                        name: {{ .Release.Name }}-{{ .Values.app.name }}-config