apiVersion: v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}-{{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
    annotations:
        external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.subdomain }}.cis240470.projects.jetstream-cloud.org
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    rules:
        - host: {{ .Values.ingress.subdomain }}.cis240470.projects.jetstream-cloud.org
          http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                      service:
                          name: {{ .Release.Name }}-{{ .Values.app.name }}
                          port:
                              number: {{ .Values.app.port }}
    tls:
        - hosts:
            - {{ .Values.ingress.subdomain }}.cis240470.projects.jetstream-cloud.org
          secretName: {{ .Release.Name }}-{{ .Values.app.name }}-tls