apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
    NODE_TLS_REJECT_UNAUTHORIZED: {{ .Values.configmap.data.NODE_TLS_REJECT_UNAUTHORIZED | quote }}
    API_BASE_URL: {{ .Values.configmap.data.API_BASE_URL | quote }}
    API_KEY: {{ .Values.configmap.data.API_KEY | quote }}