apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}-{{ .Values.app.name }}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: {{ .Values.app.port }}
    selector:
        app: {{ .Release.Name }}-{{ .Values.app.name }}