app:
  name: mswa-web
  replicas: 1
  image:
    repository: mswa/web
    tag: latest
  port: 5173

ingress:
  subdomain: mswa-web

configmap:
  data:
    API_BASE_URL: http://localhost:3000
    API_KEY: your-api-key