apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http-api-svc
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 3
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.appName }}-config
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}