apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.appName }}
spec:
  type: ClusterIP
  ports:
    - name: http-api-svc
      port: 80
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.appName }}