POST http://localhost:3000/v1/api/auth/register/emailpass
Authorization: Bearer {{$dotenv TESTING_API_KEY}}
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123456789"
}