### Login
# @name login
POST http://localhost:3000/api/v1/auth/emailpass
Authorization: Bearer {{$dotenv TESTING_API_KEY}}
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testing124"
}

### Upload Video
# @name uploadVideo
PUT http://localhost:3000/api/v1/storage/123456/sample.txt
X-User: {{login.response.body.data.token}}
Content-Type: video/mp4

< ./sample.txt