### Login
# @name login
POST http://localhost:3000/api/v1/auth/emailpass
Authorization: Bearer {{$dotenv TESTING_API_KEY}}
Content-Type: application/json

{
"email": "test@example.com",
 "password": "testing124"
}

### Get Video Presigned URL
# @name getPresignedUrl
POST http://localhost:3000/api/v1/storage/presigned-url/upload
Authorization: Bearer {{$dotenv TESTING_API_KEY}}
X-User: {{login.response.body.data.token}}
Content-Type: application/json

{
 "filePath": "videos/sample.mp4",
 "patientId": "http-client"
}

### Upload Video
# @name uploadVideo
PUT {{getPresignedUrl.response.body.data.url}}
Content-Type: multipart/form-data
X-Amz-Server-Side-Encryption-Customer-Algorithm: AES256
X-Amz-Server-Side-Encryption-Customer-Key: {{getPresignedUrl.response.body.data.encryptionKey}}
X-Amz-Server-Side-Encryption-Customer-Key-MD5: {{getPresignedUrl.response.body.data.encryptionKeyMd5}}

< sample.mp4
