apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mswa-api-pr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: mobility-scooter-project
        repo: mobility-scooter-web-app
  template:
    metadata:
      name: 'mswa-api-{{.branch | normalize}}-{{.number}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
        targetRevision: '{{.head_sha}}'
        path: 'apps/api/.kube/'
        kustomize:
          namespace: 'mswa-{{.branch | normalize}}-{{.number}}'
          labels:
            app.kubernetes.io/instance: 'mswa-{{.branch | normalize }}-{{.number}}'
            app.kubernetes.io/part-of: mobility-scooter-web-app
            app.kubernetes.io/managed-by: argocd
          components:
            - timescaledb/dev/
            - redis/dev/
          patches:
            - target:
              kind: Ingress
              name: mswa-api
              patch: |-
                - op: replace
                  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
                  value: {{.branch | normalize}}-{{.number}}.api.cis240470.projects.jetstream-cloud.org
                - op: replace
                  path: /spec/rules/0/host
                  value: {{.branch | normalize}}-{{.number}}.api.cis240470.projects.jetstream-cloud.org
                - op: replace
                  path: /spec/tls/0/hosts/0
                  value: {{.branch | normalize}}-{{.number}}.api.cis240470.projects.jetstream-cloud.org
                - op: replace
                  path: /spec/tls/0/hosts/0/secretName
                  value: {{.branch | normalize}}-{{.number}}-api-tls
      destination:
        server: https://kubernetes.default.svc
        namespace: 'mswa-{{.branch | normalize}}-{{.number}}'
      ignoreDifferences:
        - group: '*'
          kind: PersistentVolumeClaim # PR envs are ephemeral
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        automated:
          prune: true
          selfHeal: true