apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mswa-api-pvc
spec:
  storageClassName: csi-cinder-sc-retain
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce