apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mswa-api-pvc
  namespace: mswa-api
spec:
  storageClassName: csi-cinder-sc-retain
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce