[project]
name = "video-worker"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "ray (>=2.48.0)",
    "kafka-python-ng (>=2.2.0)",
    "pypino (>=0.1.0)",
    "psycopg[binary] (>=3.2.9)",
    "opencv-python-headless (>=4.10)",
    "ultralytics (>=8.3.186)",
    "python-dotenv (>=1.2.1)",
    "numpy (>=1.26)",
    "pandas (>=2.0)",
    "cupy-cuda12x (>=13.6.0)",
    "whisperx (>=3.8)",
    "google-genai (>=1.0)",
    "torch (==2.8.0)",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = {version = "==2.8.0", source = "torch_cuda"}

[[tool.poetry.source]]
name = "torch_cuda"
url = "https://download.pytorch.org/whl/cu128"
priority = "supplemental"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"