[project]
name = "video-worker"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "ray (>=2.48.0,<3.0.0)",
    "kafka-python (>=2.2.15,<3.0.0)",
    "pypino (>=0.1.0,<0.2.0)",
    "webvtt-py (>=0.5.1,<0.6.0)",
    "rapidfuzz (>=3.13.0,<4.0.0)",
    "faster-whisper (>=1.2.0,<2.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "psycopg[binary] (>=3.2.9,<4.0.0)",
    "opencv-python-headless (>=4.10)",
    "ultralytics (>=8.3.186,<9.0.0)",
    "cupy-cuda12x (>=13.6.0,<14.0.0)",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = { version = "^2.7.1", source = "torch_cuda" }

[[tool.poetry.source]]
name = "torch_cuda"
url = "https://download.pytorch.org/whl/cu128"
priority = "supplemental"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
