POST http://localhost:3000/v1/api/auth/emailpass/register
Authorization: Bearer {{$dotenv TESTING_API_KEY}}
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "testing124",
  "firstName": "Test",
  "lastName": "User",
  "unitId": "{{$dotenv TESTING_UNIT_ID}}"
}