@baseUrl = http://localhost:3000/api
@tenantId = 11111111-1111-1111-1111-111111111111
@unitId = 1
@userId = 22222222-2222-2222-2222-222222222222

### Create a new unit
POST {{baseUrl}}/tenant/{{tenantId}}/units
Content-Type: application/json

{
  "name": "Unit A"
}

### Update a unit
PUT {{baseUrl}}/tenant/{{tenantId}}/unit/{{unitId}}
Content-Type: application/json

{
  "name": "Updated Unit Name"
}

### Get all units for a tenant
GET {{baseUrl}}/tenant/{{tenantId}}/units

### Get a single unit
GET {{baseUrl}}/unit/{{unitId}}

### Delete a unit
DELETE {{baseUrl}}/unit/{{unitId}}

### Add a user to a unit
POST {{baseUrl}}/unit/{{unitId}}/users/{{userId}}

### Remove a user from a unit
DELETE {{baseUrl}}/unit/{{unitId}}/users/{{userId}}

### List all users in a unit
GET {{baseUrl}}/unit/{{unitId}}/users
