apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mswa-web
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: "msp:mswa-web-deploy"
spec:
  destination:
    namespace: mswa
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: 'https://github.com/Mobility-Scooter-Project/mobility-scooter-infra.git'
      targetRevision: main
      path: charts/api
      helm:
        values: |
          name: mswa-web
          replicas: 1
          image:
            repository: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/web
            tag: develop
            pullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          
          ingress:
            enabled: true
            subdomain: mswa.web

          database:
            enabled: false
            name: mswa-prod

          kv:
            enabled: false

          queue:
            enabled: false

          service:
            port: 3000
            targetPort: 3000
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true