web:
  image:
    tag: "latest"
  replicas: 1

api:
  image:
    tag: "latest"
  replicas: 1

# https://github.com/bitnami/charts/blob/main/bitnami/valkey/values.yaml
valkey:
  architecture: standalone
  auth:
    enabled: false
  primary:
    resourcesPreset: nano
    persistence: 
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/vault/values.yaml
vault:
  server:
    initContainers:
      - name: enable-kv
        image: docker.io/bitnami/vault:1.19.3-debian-12-r3 # make sure to update this with each helm upgrade
        env:
          - name: VAULT_ADDR
            value: http://localhost:8200
          - name: VAULT_TOKEN
            value: root
        command:
          - sh
          - -c
          - |
            # wait for Vault to come up
            until curl -s ${VAULT_ADDR}/v1/sys/health | grep -q initialized; do
              sleep 1
            done

            vault login ${VAULT_TOKEN}
            vault secrets enable -version=2 -path=secret kv

    resourcesPreset: nano
    persistence:
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  controller:
    replicaCount: 1   
    controllerOnly: false 
    resourcesPreset: micro  
    persistence:
      enabled: false          # no PVCs

  broker:
    replicaCount: 0