api:
  image:
    tag: "latest"
  replicas: 1

web:
  image:
    tag: "latest"
  replicas: 1

# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  postgresqlSharedPreloadLibraries: "pgcrypto"
  primary:
    initContainers:
      - name: apply-migrations
        image: node:20-bookworm
        env: 
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@localhost:5432
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo "Cloning repo..."
            git clone https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
            cd mobility-scooter-web-app/apps/api
            echo "Installing pnpm..."
            npm install -g pnpm
            echo "Installing drizzle..."
            pnpm i
            pnpm run db:migrate
    resourcesPreset: nano
    persistence:
      enabled: false
    initdb:
      scripts:
        create_timescaledb.sql: |
          CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

# https://github.com/bitnami/charts/blob/main/bitnami/valkey/values.yaml
valkey:
  architecture: standalone
  auth:
    enabled: false
  primary:
    resourcesPreset: nano
    persistence: 
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/vault/values.yaml
vault:
  server:
    args:
      - "server"
      - "-dev"
      - "-dev-root-token-id=root"
      - "-dev-listen-address=0.0.0.0:8200"
    lifecycleHooks:
      postStart:
        exec:
          command:
            - sh
            - -c
            - |
              # In dev mode Vault auto–initializes & unseals, so we can enable engines immediately:
              vault login root
              vault secrets enable -path=transit transit || true
              vault write -f transit/keys/object-key || true
    resourcesPreset: nano
    extraVolumes:
      - name: data
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /bitnami/vault/data
    persistence:
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  controller:
    replicaCount: 1   
    controllerOnly: false 
    resourcesPreset: micro  
    persistence:
      enabled: false          # no PVCs

  broker:
    replicaCount: 0