web:
  image:
    tag: "latest"
  replicas: 1

api:
  image:
    tag: "latest"
  replicas: 1

# https://github.com/bitnami/charts/blob/main/bitnami/valkey/values.yaml
valkey:
  architecture: standalone
  auth:
    enabled: false
  primary:
    resourcesPreset: nano
    persistence: 
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/vault/values.yaml
vault:
  server:
    args:
      - "server"
      - "-dev"
      - "-dev-root-token-id=root"
      - "-dev-listen-address=0.0.0.0:8200"
    lifecycleHooks:
      postStart:
        exec:
          command:
            - sh; -c; |
            # wait for dev Vault to be ready…
            - until curl -sf http://127.0.0.1:8200/v1/sys/health | grep -q initialized; do sleep 1; done

            - VAULT_ADDR=http://127.0.0.1:8200 vault login root

            # upgrade the built-in KV v1 at "secret/" to KV v2:
            - vault secrets tune -version=2 secret || echo "tune already applied"

            # idempotently enable Transit:
            - vault secrets enable -path=transit transit || echo "transit already enabled"
            - vault write -f transit/keys/object-key || echo "object-key exists"
    resourcesPreset: nano
    extraVolumes:
      - name: data
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /bitnami/vault/data
    persistence:
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  controller:
    replicaCount: 1   
    controllerOnly: false 
    resourcesPreset: micro  
    persistence:
      enabled: false          # no PVCs

  broker:
    replicaCount: 0