web:
  image:
    tag: "latest"
  replicas: 2

api:
  image:
    tag: "latest"
  replicas: 2

valkey:
  architecture: standalone
  auth:
    enabled: false
  persistence: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  persistence: false