web:
  image:
    tag: "latest"
  replicas: 1

api:
  image:
    tag: "latest"
  replicas: 1

# https://github.com/bitnami/charts/blob/main/bitnami/valkey/values.yaml
valkey:
  architecture: standalone
  auth:
    enabled: false
  primary:
    resourcesPreset: nano
    persistence: 
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/vault/values.yaml
vault:
  server:
    lifeCycleHooks:
      podStart:
        exec:
          command:  
          - sh
          - -c
          - |
            echo "⏳ waiting for Vault to be ready…"
            until curl -sf http://127.0.0.1:8200/v1/sys/health | grep -q initialized; do
              sleep 1
            done

            echo "🔐 logging in and enabling engines"
            VAULT_ADDR=http://127.0.0.1:8200 vault login root

            # idempotently enable KV v2
            vault secrets enable -version=2 -path=secret kv || echo "kv already enabled"

            # idempotently enable Transit and create a key
            vault secrets enable -path=transit transit || echo "transit already enabled"
            vault write -f transit/keys/object-key || echo "object-key exists"

    resourcesPreset: nano
    extraVolumes:
      - name: data
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /bitnami/vault/data
    persistence:
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  controller:
    replicaCount: 1   
    controllerOnly: false 
    resourcesPreset: micro  
    persistence:
      enabled: false          # no PVCs

  broker:
    replicaCount: 0