web:
  image:
    tag: "latest"
  replicas: 2

api:
  image:
    tag: "latest"
  replicas: 2

# https://github.com/bitnami/charts/blob/main/bitnami/valkey/values.yaml
valkey:
  architecture: standalone
  auth:
    enabled: false
  primary:
    resourcesPreset: nano
    persistence: 
      enabled: false

# https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  image:
    debug: false
  controller:
    replicaCount: 1   
    controllerOnly: false 
    resourcesPreset: micro  
    persistence:
      enabled: false          # no PVCs

  broker:
    replicaCount: 0