import { MigrationInterface, QueryRunner } from "typeorm";

export class AddVideoWorkerSchema1773780343422 implements MigrationInterface {
    name = 'AddVideoWorkerSchema1773780343422'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS "video_worker"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP CONSTRAINT "FK_442704aae057917874daeebf720"`);
        await queryRunner.query(`CREATE TABLE "video_worker"."step_status" ("videoId" uuid NOT NULL, "step" text NOT NULL, "status" text NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "lastError" text, "cuCreatedat" TIMESTAMP NOT NULL DEFAULT now(), "cuUpdatedat" TIMESTAMP, CONSTRAINT "PK_af0e564126a51c53f890e8cee32" PRIMARY KEY ("videoId", "step"))`);
        await queryRunner.query(`CREATE TABLE "video_worker"."event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "step" text NOT NULL, "status" text NOT NULL, "videoId" uuid, "cuCreatedat" TIMESTAMP NOT NULL DEFAULT now(), "cuUpdatedat" TIMESTAMP, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "videos"."video_task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tasks" jsonb NOT NULL, "videoId" uuid, "cuCreatedat" TIMESTAMP NOT NULL DEFAULT now(), "cuUpdatedat" TIMESTAMP, CONSTRAINT "UQ_226ec069c8a4f2d88fc712bdae4" UNIQUE ("videoId"), CONSTRAINT "PK_65eb0fba87a8fce66347b06c5a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "videos"."video_annotation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "targetType" text NOT NULL, "targetId" uuid, "changes" jsonb NOT NULL, "assignmentId" uuid, "videoId" uuid, "cuCreatedat" TIMESTAMP NOT NULL DEFAULT now(), "cuUpdatedat" TIMESTAMP, CONSTRAINT "PK_46cbd98f17d72fe078e882fa617" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "video_worker"."status" ("videoId" uuid NOT NULL, "statusEventId" uuid, "cuCreatedat" TIMESTAMP NOT NULL DEFAULT now(), "cuUpdatedat" TIMESTAMP, CONSTRAINT "REL_cde63259abb6942899a221cca8" UNIQUE ("statusEventId"), CONSTRAINT "PK_907153a55e6155ab1675f54527c" PRIMARY KEY ("videoId"))`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "assignmentId"`);
        await queryRunner.query(`ALTER TABLE "units"."patient" ADD "unitId" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."patient" ADD CONSTRAINT "UQ_26a9398fcdf4caf7bc9cfa7331f" UNIQUE ("unitId")`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD "patientId" uuid`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD CONSTRAINT "UQ_65356c73d71558fdb89bbfedd53" UNIQUE ("patientId")`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD "unitId" uuid`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD CONSTRAINT "UQ_733317a993491ab0fc01d067720" UNIQUE ("unitId")`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD "uploadedById" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD CONSTRAINT "UQ_6d2ab44c0a95eef23d952db9a79" UNIQUE ("uploadedById")`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD "unitId" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD CONSTRAINT "UQ_2f793e90d64306181eaf03ad4b3" UNIQUE ("unitId")`);
        await queryRunner.query(`ALTER TABLE "videos"."video" ADD "fileId" uuid`);
        await queryRunner.query(`ALTER TABLE "videos"."video" ADD CONSTRAINT "UQ_8736fb3e18f9cb3a9baacb252de" UNIQUE ("fileId")`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD "sessionId" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "UQ_54d5f4839413371d1316ef58ec7" UNIQUE ("sessionId")`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD "assignedToId" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "UQ_321b7c9b8b021bbb72c0dd66016" UNIQUE ("assignedToId")`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD "assignedById" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "UQ_89872b43ab55aa4e9058fadb9de" UNIQUE ("assignedById")`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "frameIndex" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "timestamp" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "angle" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "keypoints" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD "unitId" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD CONSTRAINT "UQ_a55a0b7a4b51ad002f4fdbee6cf" UNIQUE ("unitId")`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD "invitedById" uuid`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD CONSTRAINT "UQ_0cde52749dda28cc3f1b1aa3a05" UNIQUE ("invitedById")`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD CONSTRAINT "UQ_0289c016796a069275fed1f4d35" UNIQUE ("videoId", "frameIndex")`);
        await queryRunner.query(`ALTER TABLE "units"."patient" ADD CONSTRAINT "FK_26a9398fcdf4caf7bc9cfa7331f" FOREIGN KEY ("unitId") REFERENCES "units"."unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD CONSTRAINT "FK_65356c73d71558fdb89bbfedd53" FOREIGN KEY ("patientId") REFERENCES "units"."patient"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" ADD CONSTRAINT "FK_733317a993491ab0fc01d067720" FOREIGN KEY ("unitId") REFERENCES "units"."unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD CONSTRAINT "FK_6d2ab44c0a95eef23d952db9a79" FOREIGN KEY ("uploadedById") REFERENCES "users"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."file" ADD CONSTRAINT "FK_2f793e90d64306181eaf03ad4b3" FOREIGN KEY ("unitId") REFERENCES "units"."unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."video" ADD CONSTRAINT "FK_8736fb3e18f9cb3a9baacb252de" FOREIGN KEY ("fileId") REFERENCES "units"."file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_worker"."step_status" ADD CONSTRAINT "FK_e7825e6aac3e1a0c0972ffd3dc4" FOREIGN KEY ("videoId") REFERENCES "videos"."video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_worker"."event" ADD CONSTRAINT "FK_3d31dc538cd08efe627df783e6b" FOREIGN KEY ("videoId") REFERENCES "videos"."video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."video_task" ADD CONSTRAINT "FK_226ec069c8a4f2d88fc712bdae4" FOREIGN KEY ("videoId") REFERENCES "videos"."video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "FK_54d5f4839413371d1316ef58ec7" FOREIGN KEY ("sessionId") REFERENCES "videos"."patient_session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "FK_321b7c9b8b021bbb72c0dd66016" FOREIGN KEY ("assignedToId") REFERENCES "users"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" ADD CONSTRAINT "FK_89872b43ab55aa4e9058fadb9de" FOREIGN KEY ("assignedById") REFERENCES "users"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."video_annotation" ADD CONSTRAINT "FK_2e5be85cce08488d28d2eea7665" FOREIGN KEY ("assignmentId") REFERENCES "units"."assignment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos"."video_annotation" ADD CONSTRAINT "FK_b9ead20ef056821891896bb4d21" FOREIGN KEY ("videoId") REFERENCES "videos"."video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD CONSTRAINT "FK_a55a0b7a4b51ad002f4fdbee6cf" FOREIGN KEY ("unitId") REFERENCES "units"."unit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" ADD CONSTRAINT "FK_0cde52749dda28cc3f1b1aa3a05" FOREIGN KEY ("invitedById") REFERENCES "users"."user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_worker"."status" ADD CONSTRAINT "FK_907153a55e6155ab1675f54527c" FOREIGN KEY ("videoId") REFERENCES "videos"."video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video_worker"."status" ADD CONSTRAINT "FK_cde63259abb6942899a221cca85" FOREIGN KEY ("statusEventId") REFERENCES "video_worker"."event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP SCHEMA IF EXISTS "video_worker"`);
        await queryRunner.query(`ALTER TABLE "video_worker"."status" DROP CONSTRAINT "FK_cde63259abb6942899a221cca85"`);
        await queryRunner.query(`ALTER TABLE "video_worker"."status" DROP CONSTRAINT "FK_907153a55e6155ab1675f54527c"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP CONSTRAINT "FK_0cde52749dda28cc3f1b1aa3a05"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP CONSTRAINT "FK_a55a0b7a4b51ad002f4fdbee6cf"`);
        await queryRunner.query(`ALTER TABLE "videos"."video_annotation" DROP CONSTRAINT "FK_b9ead20ef056821891896bb4d21"`);
        await queryRunner.query(`ALTER TABLE "videos"."video_annotation" DROP CONSTRAINT "FK_2e5be85cce08488d28d2eea7665"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "FK_89872b43ab55aa4e9058fadb9de"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "FK_321b7c9b8b021bbb72c0dd66016"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "FK_54d5f4839413371d1316ef58ec7"`);
        await queryRunner.query(`ALTER TABLE "videos"."video_task" DROP CONSTRAINT "FK_226ec069c8a4f2d88fc712bdae4"`);
        await queryRunner.query(`ALTER TABLE "video_worker"."event" DROP CONSTRAINT "FK_3d31dc538cd08efe627df783e6b"`);
        await queryRunner.query(`ALTER TABLE "video_worker"."step_status" DROP CONSTRAINT "FK_e7825e6aac3e1a0c0972ffd3dc4"`);
        await queryRunner.query(`ALTER TABLE "videos"."video" DROP CONSTRAINT "FK_8736fb3e18f9cb3a9baacb252de"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP CONSTRAINT "FK_2f793e90d64306181eaf03ad4b3"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP CONSTRAINT "FK_6d2ab44c0a95eef23d952db9a79"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP CONSTRAINT "FK_733317a993491ab0fc01d067720"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP CONSTRAINT "FK_65356c73d71558fdb89bbfedd53"`);
        await queryRunner.query(`ALTER TABLE "units"."patient" DROP CONSTRAINT "FK_26a9398fcdf4caf7bc9cfa7331f"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP CONSTRAINT "UQ_0289c016796a069275fed1f4d35"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP CONSTRAINT "UQ_0cde52749dda28cc3f1b1aa3a05"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP COLUMN "invitedById"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP CONSTRAINT "UQ_a55a0b7a4b51ad002f4fdbee6cf"`);
        await queryRunner.query(`ALTER TABLE "units"."unit_invite" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "keypoints"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "angle"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "timestamp"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" DROP COLUMN "frameIndex"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "UQ_89872b43ab55aa4e9058fadb9de"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP COLUMN "assignedById"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "UQ_321b7c9b8b021bbb72c0dd66016"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP COLUMN "assignedToId"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP CONSTRAINT "UQ_54d5f4839413371d1316ef58ec7"`);
        await queryRunner.query(`ALTER TABLE "units"."assignment" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "videos"."video" DROP CONSTRAINT "UQ_8736fb3e18f9cb3a9baacb252de"`);
        await queryRunner.query(`ALTER TABLE "videos"."video" DROP COLUMN "fileId"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP CONSTRAINT "UQ_2f793e90d64306181eaf03ad4b3"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP CONSTRAINT "UQ_6d2ab44c0a95eef23d952db9a79"`);
        await queryRunner.query(`ALTER TABLE "units"."file" DROP COLUMN "uploadedById"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP CONSTRAINT "UQ_733317a993491ab0fc01d067720"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP CONSTRAINT "UQ_65356c73d71558fdb89bbfedd53"`);
        await queryRunner.query(`ALTER TABLE "videos"."patient_session" DROP COLUMN "patientId"`);
        await queryRunner.query(`ALTER TABLE "units"."patient" DROP CONSTRAINT "UQ_26a9398fcdf4caf7bc9cfa7331f"`);
        await queryRunner.query(`ALTER TABLE "units"."patient" DROP COLUMN "unitId"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "assignmentId" uuid`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD "data" jsonb NOT NULL`);
        await queryRunner.query(`DROP TABLE "video_worker"."status"`);
        await queryRunner.query(`DROP TABLE "videos"."video_annotation"`);
        await queryRunner.query(`DROP TABLE "videos"."video_task"`);
        await queryRunner.query(`DROP TABLE "video_worker"."event"`);
        await queryRunner.query(`DROP TABLE "video_worker"."step_status"`);
        await queryRunner.query(`ALTER TABLE "videos"."keypoint" ADD CONSTRAINT "FK_442704aae057917874daeebf720" FOREIGN KEY ("assignmentId") REFERENCES "units"."assignment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
