TASK_LIST = [
    "Go forward at a slow speed",  
    "Go forward at a fast speed",      
    "Go backward at a slow speed",      
    "Turn left around the cones",    
    "Turn right around the cones",      
    "Go backward and turn right",      
    "Go backward and turn left",      
    "360 degrees turning",    
    "Go forward, avoid people walking",      
    "Go forward on a soft surface 6 feet",      
    "Push the open door",      
    "Open the door and go inside",
    "Go through the automatic door",      
    "Open the door and go outside", 
    "Descends 10 degrees incline",           
    "Descends low curb",      
    "Go forward in the parking lot area avoiding cars and people",      
    "Ascends low curb",  
    "Ascends 10 degrees incline",  
    "Go through the grass",
    "Go through a gate",
    "Go over a bump",
]

KEY_WORDS = [
    "360",
    "cones",
    "avoid",
    "backing",
    "backwards",
    "backward",
    "forward",
    "grass",
    "doorway",
    "door",
    "inside",
    "outside",
    "curb",
    "avoid",
    "soft surface",
    "bump",
    "gate",
    "fast paced",
    "fast speed",
    "slow paced",
    "slow speed",
]

FILLER_PHRASES = [
    "go ahead", "gonna", "i want you to", "we", "were", "we're", "youre", "re", 
    "im", "i'm", "have to", "have you", "right back", "head back", "i need you", 
    "right now", "you are", "you're" "start", "okay", "alright", "yes", "no", "uh",
    "all righty", "just", "real quick", "alrighty", "all right", "you", "say", "i",
    "wow", "yeah", "start", "stop", "for", "me", "okay?", "what", "so", "basically",
    "all right", "go back", "come back", "want", "will", "it", "the", "me", "to", "then",
    "ll", "and", "the", "turn", "that", "can", "park"
]