apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.appName }}-service
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Release.Name }}-{{ .Values.appName}}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 80
          targetPort: http-web-svc
          protocol: TCP
    selector:
        app: {{ .Release.Name }}-{{ .Values.appName }}