TASK_LIST = [
    "Going forward at a comfortable slow speed",   
    "Going forward at a comfortable fast speed",       
    "Going backward at a comfortable slow speed",       
    "Turning left around the cone",     
    "Turning right around the cone",       
    "Go backward and turn right",      
    "Go backward and turn left",       
    "360 degrees turning",    
    "Going forward, avoid people walking",       
    "Going forward on a soft surface 6 feet",       
    "Push the open door",       
    "Go through the automatic door",       
    "Transition from outdoor to indoor to outdoor",       
    "Descends 10 degrees incline",       
    "Descends low curb",       
    "Going forward in the parking lot area avoiding cars and people",       
    "Ascends low curb",       
    "Ascends 10 degrees incline",   
]