apiVersion: apps/v1
kind: Deployment
metadata:
  name: mswa-backend
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: mswa-backend
          image: mswa-backend:latest
          ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10