apiVersion: apps/v1
kind: Deployment
metadata:
  name: mswa-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: mswa-backend
        image: ghcr.io/mobility-scooter-project/mobility-scooter-web-app/api:sha256-f603eff5fd4f0e7fd8062ea062680b4be9ad9776aaa9551139f5374dd72d69dc
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10