apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mswa-web-pr
  namespace: mswa-web
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: mobility-scooter-project
        repo: mobility-scooter-web-app
  template:
    metadata:
      name: 'mswa-web-{{.branch | normalize}}-{{.number}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-web-app.git
        path: apps/web/.kube/chart
        targetRevision: bryan/web-file-encryption
        helm:
          releaseName: 'mswa-web-{{.branch | normalize}}-{{.number}}'
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: 'mswa-{{.branch | normalize}}-{{.number}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        automated:
          prune: true
          selfHeal: true