apiVersion: v1
kind: Service
metadata:
  name: mswa-web
  namespace: mswa-web
  labels:
    app: mswa-web
spec:
  selector:
    app: mswa-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP