apiVersion: apps/v1
kind: Deployment
metadata:
  name: mswa-redis-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mswa-redis-dev
  template:
    metadata:
      labels:
        app: mswa-redis-dev
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10