apiVersion: v1
kind: Service
metadata:
  name: mswa-rabbitmq
  namespace: mswa-api
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
    